Voice/Controllers/accountController.cs
using BLL.Dto;
using BLL.Infastructure;
using BLL.Services.Sound.Editor;
using BLL.Services.Sound.GetSound;
using BLL.Services.Users;
using Microsoft.Owin.Security;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Voice.Models;
using Voice.NinjectModules;

namespace Voice.Controllers
{
    public class accountController : Controller
    {
        private IUserService _userService;
        private ISoundServiceFactory _soundServiceFactory;

        public accountController(IUserService userService, ISoundServiceFactory soundFactory)
        {
            _userService = userService;
            _soundServiceFactory = soundFactory;
        }

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

     
        public ActionResult Registration()
        {
           return View();
        }

        [HttpGet]
        public ActionResult IsUserNameBusy(string UserName)
        {
            bool busy = _userService.IsExistsUsername(UserName);
            return Json(!busy,JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public async Task<ActionResult> Registration(RegistrationModel reg)
        {
            if (ModelState.IsValid)
            {
                await SetInitialData();
                UserDto user = new UserDto() { UserName = reg.UserName, Password = reg.Password, Role = "user" };
                OperationDetails regResult = await _userService.CreateAsync(user);

                if (regResult.Successed)
                {
                    ClaimsIdentity claim = await _userService.AuthenticateAsync(user);
                    AuthenticationManager.SignIn(new AuthenticationProperties() { IsPersistent = true }, claim);
                    return View("Successed");
                }

                ModelState.AddModelError("", regResult.Message);
                return View(reg);
            }
            else
            {
                if (!ModelState.IsValidField("UserName"))
                {
                    ModelState state;
                    ModelState.TryGetValue("UserName", out state);
                    ModelState.AddModelError("UserName", state.Errors.ToString());
                }

                if (!ModelState.IsValidField("Password"))
                {
                    ModelState state;
                    ModelState.TryGetValue("Password", out state);
                    ModelState.AddModelError("Password", state.Errors.ToString());
                }
                return View(reg);
            }
        }

        public ActionResult Login()
        {
            return View();
        }


        [HttpPost]
        public async Task<ActionResult> Login(LoginModel login)
        {
            await SetInitialData();
            UserDto user = new UserDto() { UserName = login.UserName, Password = login.Password };
            ClaimsIdentity claim = await _userService.AuthenticateAsync(user);
            if(claim != null)
            {
                AuthenticationManager.SignIn(new AuthenticationProperties() { IsPersistent = true }, claim);
                return RedirectToAction("latest","sound");
            }

            ModelState.AddModelError("", "логин или пароль неверны");
            return View(login);
        }

        public ActionResult Logout()
        {
            AuthenticationManager.SignOut();
            return RedirectToAction("latest","sound");
        }

        public ActionResult Successed()
        {
            return View();
        }

        private async Task SetInitialData()
        {
            UserDto user = new UserDto() { UserName = "lesha", Password = "alex28012001", Role = "admin" };
            string[] roles = { "user", "admin" };
            await _userService.SetInitialData(user, roles);
        }


        public ActionResult profile()
        {
            return View();
        }


        [HttpPost]
        public ActionResult YourAudio(string audioTitle)
        {
            //TODO: доделать offset и count

            IGetSoundService getSound = _soundServiceFactory.CreateGetSoundService();
            string userName = User.Identity.Name;
            IEnumerable<AudioDto> userAudio = getSound.GetUserAudio(userName, 0, 10);

            return Json(userAudio);
        }

        [HttpPost]
        public void DeleteAudio(string audioTitle)
        {
            ISoundEditorService soundEditor = _soundServiceFactory.CreateSoundEditorService();
            string userName = User.Identity.Name;
            soundEditor.DeleteAudio(userName, audioTitle);
        }
    }
}

Voice/Controllers/soundController.cs
using BLL.Dto;
using BLL.Entities.Params;
using BLL.Services.Likes;
using BLL.Services.Sound.GetSound;
using BLL.Services.Sound.VisualizeSound;
using BLL.Services.Users;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using Voice.Helper;
using Voice.Models;
using Voice.NinjectModules;



namespace Voice.Controllers
{
    public class soundController : Controller
    {
        private ISoundServiceFactory _soundServiceFactory;
        private ILikeService _likeService;
        private IUserService _userService;


        public soundController(ISoundServiceFactory soundServiceFactory, ILikeService likeService,
                               IUserService userService)
        {
            _soundServiceFactory = soundServiceFactory;
            _likeService = likeService;
            _userService = userService;
        }


        public ActionResult author(AuthorModel model)
        {
            if (!String.IsNullOrEmpty(model.audioTitle))
            {
                IGetSoundService getSoundService = _soundServiceFactory.CreateGetSoundService();
                AudioDto audio = getSoundService.FindAudio(model.Name, model.audioTitle);

                if(audio == null)
                    return View("UserAudioNotExists", "_Layout", model);

                return View("track", audio);
            }
            else
            {
                if (!_userService.IsExistsUsername(model.Name))
                    return View("UserNotExists", "_Layout", model.Name);
                        
                return View("author", "_Layout", model.Name);
            }
        }



        public ActionResult search(string name)
        {
            return View((object)name);
        }


        [HttpPost]
        public ActionResult FindAudio(string audioTitle)
        {
            //TODO: доделать offset и count для возвращения аудио
            IGetSoundService getSoundService = _soundServiceFactory.CreateGetSoundService();
            IEnumerable<AudioDto> foundAudio = getSoundService.FindAudio(audioTitle, 0, 10);

            return Json(foundAudio);
        }



        [HttpGet]
        public ActionResult latest()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LatestAudio()
        {
            //TODO: доделать offset и count для возвращения аудио
            IGetSoundService getSoundService = _soundServiceFactory.CreateGetSoundService();
            IEnumerable<AudioDto> newAudio = getSoundService.GetNewAudio(0, 10);

            return Json(newAudio);
        }



        [HttpGet]
        public ActionResult popular()
        {
            return View();
        }

        [HttpPost]
        public ActionResult PopularAudio()
        {
            //TODO: доделать offset и count для возвращения аудио
            IGetSoundService getSoundService = _soundServiceFactory.CreateGetSoundService();
            IEnumerable<AudioDto> popularAudio = getSoundService.GetPopularAudio(0, 10);

            return Json(popularAudio);
        }


        [HttpPost]
        public ActionResult UserAudio(string userName)
        {
            //TODO: доделать offset и count для возвращения аудио
            IGetSoundService getSoundService = _soundServiceFactory.CreateGetSoundService();
            IEnumerable<AudioDto> userAudio = getSoundService.GetUserAudio(userName, 0, 10);

            return Json(userAudio);
        }


        [HttpGet]
        public ActionResult subs()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SubsAudio()
        {
            //TODO: доделать offset и count для возвращения аудио
            IGetSoundService getSoundService = _soundServiceFactory.CreateGetSoundService();
            string userName = User.Identity.Name;
            IEnumerable<AudioDto> subsAudio = getSoundService.GetSubAudio(userName, 0, 10);

            return Json(subsAudio);
        }
        


        [HttpGet]
        public ActionResult liked()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LikedAudio()
        {
            //TODO: доделать offset и count для возвращения аудио
            IGetSoundService getSoundService = _soundServiceFactory.CreateGetSoundService();
            string userName = User.Identity.Name;
            IEnumerable<AudioDto> likedAudio = getSoundService.GetLikedAudio(userName, 0, 10);

            return Json(likedAudio);
        }




        [HttpPost]
        public async Task<ActionResult> Player(PlayerModel model)
        {
            IVisualizatorService visualizatorService = _soundServiceFactory.CreateVisualizatorService();
            DataForPlayer dataForPlayer = new DataForPlayer() { Audio = model.Audio, PlayerProperties = model.PlayerProperties };

            string userName = User.Identity.Name;
            AudioMarkParams likeParams = new AudioMarkParams(userName, model.Audio.UserName, model.Audio.Title);
            bool isLiked = await _likeService.IsLikedAsync(likeParams);
            dataForPlayer.IsLiked = isLiked;

            string audioWebSitePath = model.Audio.Src.Replace("/", "\\");
            string pathToServer = AppDomain.CurrentDomain.BaseDirectory;
            string audioServerPath = $"{pathToServer}\\{audioWebSitePath}";

            string playerHtml = RenderView.RenderViewToString(this.ControllerContext, "Player", dataForPlayer);

            IEnumerable<int> dataToVisualise = visualizatorService.Visualize(audioServerPath, model.AmountProc);
            OutputPlayer visPlayer = new OutputPlayer() { Playerhtml = playerHtml, DataToVisualize = dataToVisualise };

            return Json(visPlayer);
        }


        [HttpPost]
        public ActionResult AudioRoad(string userName, string audioTitle, int amountProc)
        {
            IVisualizatorService visualizatorService = _soundServiceFactory.CreateVisualizatorService();

            string pathToServer = AppDomain.CurrentDomain.BaseDirectory;
            var audioServerPath = $"{pathToServer}Audio\\{userName}\\{audioTitle}.wav";

            IEnumerable<int> dataToVisualise = visualizatorService.Visualize(audioServerPath, amountProc);
            return Json(dataToVisualise);
        }


        public ActionResult UserNotExists(string userName)
        {
            return View(userName);
        }

        public ActionResult UserAudioNotExists(AuthorModel model)
        {
            return View(model);
        }
    }
}

Voice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet"/>
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/modernizr") 

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>      
                <div class="header-brand">
                    @Html.ActionLink("Voice", "latest", "sound", new { area = "" }, new { @class = "navbar-brand" })
                </div>
            </div>
                    


            <div class="navbar-collapse collapse">

                <ul class="nav navbar-nav">
                     <li>
                       @Html.ActionLink("Index", "latest", "sound")
                    </li>
                </ul>

             
           
                @*<div class="navbar-form" style="display:inline-block">        
                    <div class="input-group">
                        <input type="text" class="navbar-text-box form-control" placeholder="Поиск" />
                        <span class="input-group-addon">S</span>   
                    </div>           
               </div>*@


                <div class="navbar-form" style="display:inline-block">
                    <div class="input-group">
                        <input type="text" class="form-control" name="search-audio-area" />
                        <span class="input-group-addon" name="search-audio-btn">S</span>
                    </div>
                </div>
             
         
            
                    @if (User.Identity.IsAuthenticated)
                    {
                       <ul class="nav navbar-nav">
                           <li>
                               @Html.ActionLink(User.Identity.Name, "profile", "account")
                           </li>
                           <li>
                               @Html.ActionLink("Logout", "Logout", "account")
                           </li>        
                       </ul> 
                    }

                    else
                    {
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                @Html.ActionLink("Registration", "Registration", "account")
                            </li>
                            <li>
                                @Html.ActionLink("Log in", "Login", "account")
                            </li>
                        </ul>
                    }
            
            </div>          
        </div>
    </div>
    
    <div class="container body-content">
        @RenderBody()   
    </div>
   
      
       
  

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/player.js"></script>
    <script src="~/Scripts/layout.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>