Voice/Controllers/buildSoundController.cs
using BLL.Dto;
using BLL.Entities;
using BLL.Entities.Params.BuildSoundParam;
using BLL.Entities.Params.SavedSoundParam;
using BLL.Infastructure;
using BLL.Services.Letters;
using BLL.Services.Sound.BuildSound;
using BLL.Services.Sound.Editor;
using System;
using System.IO;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Voice.Models;
using Voice.NinjectModules;

namespace Voice.Controllers
{
    public class buildSoundController : Controller
    {
        private ISoundServiceFactory _soundServiceFactory;
        private ILetterService _letterService;

        public buildSoundController(ISoundServiceFactory soundServiceFactory, ILetterService letterService)
        {
            _soundServiceFactory = soundServiceFactory;
            _letterService = letterService;
        }

        public ActionResult create()
        {
            return View();
        }

        //TASK: сделать выбор языка
        //TASK: сделать проверку на запись всех букв по заданному языку
        [HttpPost]
        public ActionResult create(BuildSoundModel model)
        {
            IBuilderSoundService builderSoundService = _soundServiceFactory.CreateBuilderSoundService();

            BuildSoundParams buildSoundParam = new BuildSoundParams()
            { Text = model.Text, Language = model.Language, UserName = User.Identity.Name,
              Volume = model.PercentVolume, SampleRate = model.SampleRate };

            ResultDetails<Stream> resultBuildingSound = builderSoundService.BuildSound(buildSoundParam);

            if (!resultBuildingSound.Successed)
                return new EmptyResult();  

            Stream soundStream = resultBuildingSound.Data;
            Response.AppendHeader("Content-Length", soundStream.Length.ToString());
            Response.AppendHeader("Accept-Ranges", "bytes");

            return File(soundStream, "audio/wav");
        }


        [HttpPost]
        public ActionResult IsVoiceRecorded(Language language)
        {
            string userName = User.Identity.Name;
            bool isVoiceRecorded = _letterService.IsVoiceRecoreded(userName, language);
            return Json(isVoiceRecorded);
        }

      
        [HttpPost]
        public async Task<ActionResult> saveAudioByStream()
        {
            ISoundEditorService soundEditor = _soundServiceFactory.CreateSoundEditorService();

            HttpPostedFileBase audio = Request.Files["waveFile"];
            string title = Request.Form["title"];
            string text = Request.Form["text"];

            AudioDto audioDto = new AudioDto()
            { Title = title,Text = text, UserName = User.Identity.Name,Date = DateTime.UtcNow };
            SaveAudioByStreamParams param = new SaveAudioByStreamParams(audio.InputStream, audioDto);
            OperationDetails resultSaveAudio = await soundEditor.SaveAudioByStreamAsync(param);

            string resultStr = resultSaveAudio.Successed ? "Аудио успешно сохранено" : "текст должен содержать хотя-бы 1 алфавитно-символьный символ";
            return Content(resultStr);
        }


        [HttpPost]
        public async Task<ActionResult> saveAudioByText(string text, string title,Language Language, int sampleRate)
        {
            ISoundEditorService soundEditor = _soundServiceFactory.CreateSoundEditorService();

            AudioDto audioDto = new AudioDto()
            { Title = title, Text = text, UserName = User.Identity.Name, Date = DateTime.UtcNow };
            SaveAudioByTextParams param = new SaveAudioByTextParams
            (text, audioDto, Language.rus, sampleRate);

            OperationDetails resultSaveAudio = await soundEditor.SaveAudioByTextAsync(param);

            string resultStr = resultSaveAudio.Successed ? "Аудио успешно сохранено" : "текст должен содержать хотя-бы 1 алфавитно-символьный символ";
            return Content(resultStr);
        }
    }
}

Voice/Controllers/recordController.cs
using BLL.Dto;
using BLL.Entities;
using BLL.Entities.Params.SavedSoundParam;
using BLL.Infastructure;
using BLL.Services.Letters;
using System;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Voice.Controllers
{
    public class recordController : Controller
    {
        private ILetterService _letterService;

        public recordController(ILetterService letterService)
        {
            _letterService = letterService;
        }

        public ActionResult letters()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> letterIsRecord(string letterName)
        {
            bool isRecord = await _letterService.IsLetterRecordedAsync(User.Identity.Name, letterName);
            return Json(isRecord);
        }


        //TODO: сделать проверку на вес записанной буквы
        [HttpPost]
        public async Task<ActionResult> saveLetter()
        {
            HttpPostedFileBase audio = Request.Files["waveFile"];
            string word = Request.Form["word"];
            int sampleRate = Convert.ToInt32(Request.Form["sampleRate"]);
            int channels = Convert.ToInt32(Request.Form["channels"]);

            LetterDto letterDto = new LetterDto()
            { LetterName = word, Language = Language.rus, UserName = User.Identity.Name };

            SaveLetterParams param = new SaveLetterParams(audio.InputStream, letterDto, sampleRate, channels);
            OperationDetails opDetails = await _letterService.SaveLetterAsync(param);
            return Json(opDetails.Successed);
        }

    }
}

Voice/Controllers/soundController.cs
using BLL.Dto;
using BLL.Entities.Params;
using BLL.Services.Likes;
using BLL.Services.Sound.GetSound;
using BLL.Services.Sound.VisualizeSound;
using BLL.Services.Users;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using Voice.Helper;
using Voice.Models;
using Voice.NinjectModules;



namespace Voice.Controllers
{
    public class soundController : Controller
    {
        private ISoundServiceFactory _soundServiceFactory;
        private ILikeService _likeService;
        private IUserService _userService;


        public soundController(ISoundServiceFactory soundServiceFactory, ILikeService likeService,
                               IUserService userService)
        {
            _soundServiceFactory = soundServiceFactory;
            _likeService = likeService;
            _userService = userService;
        }


        public ActionResult author(AuthorModel model)
        {
            if (!String.IsNullOrEmpty(model.audioTitle))
            {
                IGetSoundService getSoundService = _soundServiceFactory.CreateGetSoundService();
                AudioDto audio = getSoundService.FindAudio(model.Name, model.audioTitle);

                if(audio == null)
                    return View("UserAudioNotExists", "_Layout", model);

                return View("track", audio);
            }
            else
            {
                if (!_userService.IsExistsUsername(model.Name))
                    return View("UserNotExists", "_Layout", model.Name);
                        
                return View("author", "_Layout", model.Name);
            }
        }



        public ActionResult search(string name)
        {
            return View((object)name);
        }


        [HttpPost]
        public ActionResult FindAudio(string audioTitle)
        {
            //TODO: доделать offset и count для возвращения аудио
            IGetSoundService getSoundService = _soundServiceFactory.CreateGetSoundService();
            IEnumerable<AudioDto> foundAudio = getSoundService.FindAudio(audioTitle, 0, 10);

            return Json(foundAudio);
        }



        [HttpGet]
        public ActionResult latest()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LatestAudio()
        {
            //TODO: доделать offset и count для возвращения аудио
            IGetSoundService getSoundService = _soundServiceFactory.CreateGetSoundService();
            IEnumerable<AudioDto> newAudio = getSoundService.GetNewAudio(0, 10);

            return Json(newAudio);
        }



        [HttpGet]
        public ActionResult popular()
        {
            return View();
        }

        [HttpPost]
        public ActionResult PopularAudio()
        {
            //TODO: доделать offset и count для возвращения аудио
            IGetSoundService getSoundService = _soundServiceFactory.CreateGetSoundService();
            IEnumerable<AudioDto> popularAudio = getSoundService.GetPopularAudio(0, 10);

            return Json(popularAudio);
        }


        [HttpPost]
        public ActionResult UserAudio(string userName)
        {
            //TODO: доделать offset и count для возвращения аудио
            IGetSoundService getSoundService = _soundServiceFactory.CreateGetSoundService();
            IEnumerable<AudioDto> userAudio = getSoundService.GetUserAudio(userName, 0, 10);

            return Json(userAudio);
        }


        [HttpGet]
        public ActionResult subs()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SubsAudio()
        {
            //TODO: доделать offset и count для возвращения аудио
            IGetSoundService getSoundService = _soundServiceFactory.CreateGetSoundService();
            string userName = User.Identity.Name;
            IEnumerable<AudioDto> subsAudio = getSoundService.GetSubAudio(userName, 0, 10);

            return Json(subsAudio);
        }
        


        [HttpGet]
        public ActionResult liked()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LikedAudio()
        {
            //TODO: доделать offset и count для возвращения аудио
            IGetSoundService getSoundService = _soundServiceFactory.CreateGetSoundService();
            string userName = User.Identity.Name;
            IEnumerable<AudioDto> likedAudio = getSoundService.GetLikedAudio(userName, 0, 10);

            return Json(likedAudio);
        }




        [HttpPost]
        public async Task<ActionResult> Player(PlayerModel model)
        {
            IVisualizatorService visualizatorService = _soundServiceFactory.CreateVisualizatorService();
            DataForPlayer dataForPlayer = new DataForPlayer() { Audio = model.Audio, PlayerProperties = model.PlayerProperties };

            string userName = User.Identity.Name;
            AudioMarkParams likeParams = new AudioMarkParams(userName, model.Audio.UserName, model.Audio.Title);
            bool isLiked = await _likeService.IsLikedAsync(likeParams);
            dataForPlayer.IsLiked = isLiked;

            string audioWebSitePath = model.Audio.Src.Replace("/", "\\");
            string pathToServer = AppDomain.CurrentDomain.BaseDirectory;
            string audioServerPath = $"{pathToServer}\\{audioWebSitePath}";

            string playerHtml = RenderView.RenderViewToString(this.ControllerContext, "Player", dataForPlayer);

            IEnumerable<int> dataToVisualise = visualizatorService.Visualize(audioServerPath, model.AmountProc);
            OutputPlayer visPlayer = new OutputPlayer() { Playerhtml = playerHtml, DataToVisualize = dataToVisualise };

            return Json(visPlayer);
        }


        [HttpPost]
        public ActionResult AudioRoad(string userName, string audioTitle, int amountProc)
        {
            IVisualizatorService visualizatorService = _soundServiceFactory.CreateVisualizatorService();

            string pathToServer = AppDomain.CurrentDomain.BaseDirectory;
            var audioServerPath = $"{pathToServer}Audio\\{userName}\\{audioTitle}.wav";

            IEnumerable<int> dataToVisualise = visualizatorService.Visualize(audioServerPath, amountProc);
            return Json(dataToVisualise);
        }


        public ActionResult UserNotExists(string userName)
        {
            return View(userName);
        }

        public ActionResult UserAudioNotExists(AuthorModel model)
        {
            return View(model);
        }
    }
}

Voice/Views/sound/Player.cshtml
@model Voice.Models.DataForPlayer
@{
    string likeUnlike = Model.IsLiked ? "like" : "unlike";
    
}

<div class="player" audio-path="@Model.Audio.Src" audio-road="" data-currentTime="0">

    <div class="sound-header">
        <div class="singer-name">
            <a class="title-text" href="/sound/author/@Model.Audio.UserName">@Model.Audio.UserName</a>
        </div>

        <span class="title-separator">/</span>

        <div class="audio-title">
            <a class="title-text" href="/sound/author/@Model.Audio.UserName/@Model.Audio.Title">@Model.Audio.Title</a>
        </div>
        <div class="audio-date">
            <span>@Model.Audio.Date.ToShortDateString() @Model.Audio.Date.ToShortTimeString()</span>
        </div>
    </div>



    <div class="sound-body">
        <div class="play-btn">
            <span class="fa fa-play"></span>
        </div>

        <div class="sound-road">
            <canvas width="@Model.PlayerProperties.CanvasWidth" height="@Model.PlayerProperties.CanvasHeight" data-work="off"></canvas>
        </div> 
    </div>




    <div class="sound-footer">
        <div class="mark">
            <div class="@likeUnlike" name="mark">
                <span class="fa fa-heart"></span>
            </div>

            <span class="count-likes">
                @Model.Audio.QuantityLikes
            </span>
        </div>


        <div class="listening">
            <span class="listening-text">Прослушано:</span>
            <span class="listening-count"> @Model.Audio.Listening</span>
        </div>

        <div class="comments">
            <span class="fa fa-comment-o" style="font-size:120%"></span>
            <span class="comments-count">@Model.Audio.QuantityComments</span>
        </div>
    </div>

</div>

Voice/Views/sound/UserAudioNotExists.cshtml
@model Voice.Models.AuthorModel
@{
    ViewBag.Title = "AudioNotExists";
}

<center>
    <h2>
        У пользователя
        <span style="font-weight:600;">@Model.SingerName</span>
        нет аудио под именем
        <span style="font-weight:600;">@Model.AudioTitle</span>
    </h2>
</center>

Voice/Views/sound/UserNotExists.cshtml
@model string
@{
    ViewBag.Title = "UserNotExists";
}

<center>
    <h2>Пользователя @Model не существует</h2>
</center>

Voice/Views/sound/author.cshtml
@model string
@{
    ViewBag.Title = "track";
}

<h2>@Model</h2>
<div class="follow" name="sub">
    подписаться
</div>

<div class="audio-container"></div>

@section scripts
{
   <script src="~/Scripts/player.js"></script>
    <script type="text/javascript">
        var singerName = "@Model";
    </script>
    <script src="~/Scripts/author.js"></script>
}

Voice/Views/sound/latest.cshtml
@{
    ViewBag.Title = "latest";
}

@Html.ActionLink("Запись голоса", "letters", "record")
@Html.ActionLink("Создание аудио", "create", "buildSound")

<h2>новые аудио</h2>


<a href="/sound/popular">
    <input type="submit" value="популярные аудио"/>
</a>

<a href="/sound/liked">
    <input type="submit" value="понравившиеся аудио" />
</a>

<a href="/sound/subs">
    <input type="submit" value="подписки" />
</a>

<a href="/account/profile">
    <input type="submit" value="профиль" />
</a>

<div class="audio-container"></div>

@section scripts
{
    <script src="~/Scripts/player.js"></script>
    <script src="~/Scripts/latest-audio.js"></script>
}

Voice/Views/sound/liked.cshtml
@{
    ViewBag.Title = "liked";
}

@Html.ActionLink("Запись голоса", "letters", "record")
@Html.ActionLink("Создание аудио", "create", "buildSound")

<h2>понравившиеся аудио</h2>


<a href="/sound/latest">
    <input type="submit" value="новые аудио" />
</a>

<a href="/sound/popular">
    <input type="submit" value="популярные аудио" />
</a>

<a href="/sound/subs">
    <input type="submit" value="подписки" />
</a>

<a href="/account/profile">
    <input type="submit" value="профиль" />
</a>

<div class="audio-container"></div>

@section scripts
{
    <script src="~/Scripts/player.js"></script>
    <script src="~/Scripts/liked-audio.js"></script>
}

Voice/Views/sound/popular.cshtml
@{
    ViewBag.Title = "popular";
}

@Html.ActionLink("Запись голоса", "letters", "record")
@Html.ActionLink("Создание аудио", "create", "buildSound")

<h2>Популярные</h2>

<a href="/sound/latest">
    <input type="submit" value="новые аудио"/>
</a>

<a href="/sound/liked">
    <input type="submit" value="понравившиеся аудио" />
</a>


<a href="/sound/subs">
    <input type="submit" value="подписки"/>
</a>

<a href="/account/profile">
    <input type="submit" value="профиль" />
</a>


<div class="audio-container"></div>

@section scripts
{
    <script src="~/Scripts/player.js"></script>
    <script src="~/Scripts/popular-audio.js"></script>
}

Voice/Views/sound/search.cshtml
@model string

@{
    ViewBag.Title = "search";
}

<h2>search</h2>
<div class="audio-container"></div>

@section scripts
{
    <script src="~/Scripts/player.js"></script>
    <script type="text/javascript">
        var audioTitle = "@Model";
    </script>
    <script src="~/Scripts/search-audio.js"></script>
}

Voice/Views/sound/subs.cshtml
@{
    ViewBag.Title = "subs";
}

<h2>подписки</h2>
<div class="audio-container"></div>

@section scripts
{
    <script src="~/Scripts/player.js"></script>
    <script src="~/Scripts/subs-audio.js"></script>
}

Voice/Views/sound/track.cshtml
@model BLL.Dto.AudioDto
@{
    ViewBag.Title = "track"; 
}

<h2>track</h2>
<div class="audio-container"></div>

<div class="audio-text-container">
    <h2>@Model.Text</h2>
</div>

<div class="comments-container"></div>


@section scripts
{
    <script type="text/javascript">
        var userName = "@Model.UserName";
        var audioTitle = "@Model.Title";
        var audioPath = "@Model.Src";
        var quantityLikes = "@Model.QuantityLikes";
        var quantityComments = "@Model.QuantityComments";
        var listening = "@Model.Listening";
        var date = "@Model.Date";
    </script>

    <script src="~/Scripts/one-track.js"></script>
    <script src="~/Scripts/comments.js"></script>
}